// Mots-clés : des noms concrets ou évocateurs, riches en associations,
// sans noms propres ni mots trop rares.
export const WORDS: readonly string[] = [
  // Nature et paysages
  "VOLCAN", "DÉSERT", "GLACIER", "FORÊT", "RIVIÈRE", "OCÉAN", "ÎLE", "MONTAGNE",
  "CASCADE", "PRAIRIE", "MARAIS", "GROTTE", "FALAISE", "DUNE", "LAGON", "COLLINE",
  "VALLÉE", "CANYON", "JUNGLE", "BANQUISE", "ORAGE", "ÉCLAIR", "NEIGE", "BROUILLARD",
  "ARC-EN-CIEL", "TORNADE", "SÉISME", "MARÉE", "VAGUE", "SOURCE", "PLAGE", "RÉCIF",
  "ÉTOILE", "LUNE", "SOLEIL", "COMÈTE", "ÉCLIPSE", "GALAXIE", "PLANÈTE", "AURORE",
  "CRÉPUSCULE", "NUAGE", "PLUIE", "GRÊLE", "VENT", "TONNERRE", "ROSÉE", "GIVRE",

  // Animaux
  "BALEINE", "REQUIN", "PIEUVRE", "DAUPHIN", "MÉDUSE", "CRABE", "HOMARD", "TORTUE",
  "AIGLE", "HIBOU", "CORBEAU", "PERROQUET", "PINGOUIN", "FLAMANT", "PAON", "COLIBRI",
  "LION", "TIGRE", "LOUP", "RENARD", "OURS", "ÉLÉPHANT", "GIRAFE", "ZÈBRE",
  "SINGE", "GORILLE", "KANGOUROU", "CHAMEAU", "CHEVAL", "LICORNE", "DRAGON", "SERPENT",
  "CROCODILE", "CAMÉLÉON", "GRENOUILLE", "ARAIGNÉE", "ABEILLE", "FOURMI", "PAPILLON", "SCORPION",
  "ESCARGOT", "HÉRISSON", "CASTOR", "CHAUVE-SOURIS", "LAPIN", "HAMSTER", "CHAT", "CHIEN",
  "VACHE", "COCHON", "MOUTON", "POULE", "CYGNE", "PHÉNIX", "DINOSAURE", "MAMMOUTH",

  // Nourriture et boissons
  "PIZZA", "FROMAGE", "CHOCOLAT", "BAGUETTE", "CROISSANT", "CRÊPE", "GÂTEAU", "BONBON",
  "MIEL", "CONFITURE", "BEURRE", "SUCRE", "SEL", "POIVRE", "MOUTARDE", "VANILLE",
  "CITRON", "ORANGE", "POMME", "BANANE", "FRAISE", "CERISE", "ANANAS", "NOIX DE COCO",
  "TOMATE", "CAROTTE", "OIGNON", "CHAMPIGNON", "PIMENT", "AIL", "POTIRON", "SALADE",
  "SOUPE", "SUSHI", "OMELETTE", "FRITES", "POPCORN", "GLACE", "CAFÉ", "THÉ",
  "VIN", "CHAMPAGNE", "BIÈRE", "LAIT", "JUS", "SIROP", "PAIN", "ŒUF",

  // Maison et objets
  "CLÉ", "SERRURE", "PORTE", "FENÊTRE", "ESCALIER", "GRENIER", "CAVE", "CHEMINÉE",
  "LAMPE", "BOUGIE", "MIROIR", "HORLOGE", "RÉVEIL", "CANAPÉ", "LIT", "OREILLER",
  "COUVERTURE", "ARMOIRE", "TIROIR", "VALISE", "PARAPLUIE", "LUNETTES", "MONTRE", "BAGUE",
  "COLLIER", "COURONNE", "CHAPEAU", "ÉCHARPE", "GANT", "BOTTE", "CRAVATE", "MASQUE",
  "CISEAUX", "AIGUILLE", "BOUTON", "FIL", "MARTEAU", "CLOU", "VIS", "ÉCHELLE",
  "SEAU", "BALAI", "ÉPONGE", "SAVON", "BROSSE", "PEIGNE", "SERVIETTE", "BAIGNOIRE",
  "FOURCHETTE", "COUTEAU", "CUILLÈRE", "ASSIETTE", "VERRE", "BOUTEILLE", "CASSEROLE", "FOUR",
  "FRIGO", "TÉLÉPHONE", "TÉLÉCOMMANDE", "ÉCRAN", "CLAVIER", "CAMÉRA", "RADIO", "ANTENNE",

  // Lieux
  "CHÂTEAU", "PHARE", "MOULIN", "CATHÉDRALE", "PYRAMIDE", "TEMPLE", "MUSÉE", "BIBLIOTHÈQUE",
  "HÔPITAL", "PRISON", "ÉCOLE", "CIRQUE", "CINÉMA", "THÉÂTRE", "STADE", "PISCINE",
  "GARE", "AÉROPORT", "PORT", "MARCHÉ", "BOULANGERIE", "PHARMACIE", "BANQUE", "CASINO",
  "FERME", "USINE", "MINE", "LABORATOIRE", "BUNKER", "LABYRINTHE", "CIMETIÈRE", "JARDIN",
  "PONT", "TUNNEL", "TOUR", "RUINE", "OASIS", "IGLOO", "CABANE", "TENTE",
  "PALAIS", "DONJON", "ARÈNE", "ÉGOUT", "MÉTRO", "AUTOROUTE", "CARREFOUR", "FRONTIÈRE",

  // Transports et machines
  "TRAIN", "AVION", "FUSÉE", "SOUS-MARIN", "BATEAU", "VOILIER", "RADEAU", "HÉLICOPTÈRE",
  "MONTGOLFIÈRE", "VÉLO", "MOTO", "CAMION", "TRACTEUR", "AMBULANCE", "TAXI", "BUS",
  "TRAÎNEAU", "SKATE", "ROLLER", "TÉLÉPHÉRIQUE", "ASCENSEUR", "ROBOT", "MOTEUR", "ROUE",
  "SATELLITE", "DRONE", "RADAR", "BOUSSOLE", "TÉLESCOPE", "MICROSCOPE", "LOUPE", "AIMANT",
  "BATTERIE", "CÂBLE", "AMPOULE", "LASER", "ENGRENAGE", "PISTON", "HÉLICE", "PARACHUTE",

  // Métiers et personnages
  "PIRATE", "CHEVALIER", "SORCIER", "FÉE", "GÉANT", "NAIN", "VAMPIRE", "FANTÔME",
  "ZOMBIE", "MOMIE", "SIRÈNE", "OGRE", "ROI", "REINE", "PRINCESSE", "DUC",
  "ESPION", "DÉTECTIVE", "POLICIER", "VOLEUR", "JUGE", "AVOCAT", "MÉDECIN", "INFIRMIER",
  "CUISINIER", "BOULANGER", "PÊCHEUR", "BERGER", "FACTEUR", "POMPIER", "PILOTE", "ASTRONAUTE",
  "CLOWN", "MAGICIEN", "ACROBATE", "JONGLEUR", "DANSEUR", "CHANTEUR", "PEINTRE", "SCULPTEUR",
  "SAMOURAÏ", "NINJA", "VIKING", "COW-BOY", "GLADIATEUR", "MOINE", "EXPLORATEUR", "SCIENTIFIQUE",

  // Corps et santé
  "CŒUR", "CERVEAU", "ŒIL", "OREILLE", "NEZ", "BOUCHE", "DENT", "LANGUE",
  "MAIN", "DOIGT", "PIED", "GENOU", "ÉPAULE", "DOS", "OS", "SQUELETTE",
  "SANG", "LARME", "SOURIRE", "BARBE", "MOUSTACHE", "CHEVEU", "PEAU", "OMBRE",
  "RÊVE", "CAUCHEMAR", "SOMMEIL", "FIÈVRE", "VACCIN", "PANSEMENT", "PILULE", "SERINGUE",

  // Culture, loisirs et jeux
  "PIANO", "GUITARE", "VIOLON", "TAMBOUR", "TROMPETTE", "HARPE", "FLÛTE", "ORCHESTRE",
  "OPÉRA", "BALLET", "DISCO", "RAP", "JAZZ", "MICRO", "CONCERT", "KARAOKÉ",
  "LIVRE", "POÈME", "ROMAN", "BANDE DESSINÉE", "JOURNAL", "LETTRE", "TIMBRE", "CARTE",
  "ÉCHECS", "DOMINO", "DÉ", "PUZZLE", "POKER", "BALLON", "RAQUETTE", "FILET",
  "BOXE", "JUDO", "SKI", "SURF", "GOLF", "TENNIS", "FOOTBALL", "MARATHON",
  "MÉDAILLE", "TROPHÉE", "PODIUM", "ARBITRE", "SIFFLET", "CHRONOMÈTRE", "RECORD", "CHAMPION",
  "FILM", "SÉRIE", "DESSIN ANIMÉ", "PHOTO", "TABLEAU", "STATUE", "MARIONNETTE", "COSTUME",
  "FÊTE", "ANNIVERSAIRE", "MARIAGE", "NOËL", "CARNAVAL", "FEU D'ARTIFICE", "CADEAU", "GUIRLANDE",

  // Nature végétale et matières
  "ROSE", "TULIPE", "TOURNESOL", "CACTUS", "PALMIER", "SAPIN", "CHÊNE", "BAMBOU",
  "RACINE", "FEUILLE", "GRAINE", "ÉPINE", "LIERRE", "MOUSSE", "ALGUE", "NÉNUPHAR",
  "OR", "ARGENT", "FER", "CUIVRE", "DIAMANT", "RUBIS", "PERLE", "CRISTAL",
  "PAPIER", "CARTON", "PLASTIQUE", "BÉTON", "BOIS", "PIERRE", "SABLE", "BOUE",
  "SOIE", "LAINE", "CUIR", "PLUME", "CIRE", "CHARBON", "PÉTROLE", "FUMÉE",

  // Abstrait et mystère
  "SECRET", "MYSTÈRE", "ÉNIGME", "LÉGENDE", "MYTHE", "PROPHÉTIE", "MALÉDICTION", "TRÉSOR",
  "COFFRE-FORT", "CODE", "SIGNAL", "MESSAGE", "ALARME", "RANÇON", "PIÈGE", "COMPLOT",
  "MÉMOIRE", "SILENCE", "ÉCHO", "VERTIGE", "MIRAGE", "PARADOXE", "HASARD", "DESTIN",
  "GUERRE", "PAIX", "RÉVOLUTION", "EMPIRE", "COLONIE", "ÉLECTION", "IMPÔT", "LOI",
  "TEMPS", "HISTOIRE", "FUTUR", "PASSÉ", "MINUIT", "AUBE", "WEEK-END", "VACANCES",
  "ARMÉE", "ÉPÉE", "BOUCLIER", "ARBALÈTE", "FLÈCHE", "CANON", "BOMBE", "ARMURE",
  "VIRUS", "ROBINET", "PRISME", "SPIRALE", "TOTEM", "RELIQUE", "SCEPTRE", "ORACLE",
  "NÉON", "PLASMA", "ATOME", "ÉLECTRON", "GRAVITÉ", "TROU NOIR", "ÉNERGIE", "RADIATION",
  "ZÉRO", "INFINI", "CERCLE", "TRIANGLE", "CARRÉ", "CROIX", "HEXAGONE", "POINT",

  // Vie quotidienne
  "MONNAIE", "PORTEFEUILLE", "TICKET", "PASSEPORT", "BAGAGE", "PLAN", "CALENDRIER", "AGENDA",
  "RÉUNION", "BUREAU", "PATRON", "SALAIRE", "GRÈVE", "RETRAITE", "DIPLÔME", "EXAMEN",
  "CRAIE", "TROUSSE", "CARTABLE", "STYLO", "CRAYON", "GOMME", "RÈGLE", "COMPAS",
  "POUBELLE", "RECYCLAGE", "EMBOUTEILLAGE", "LAMPADAIRE", "PARKING", "PÉAGE", "PNEU", "ESSENCE",
  "BÉBÉ", "BIBERON", "BERCEAU", "JOUET", "TOUPIE", "CERF-VOLANT", "BALANÇOIRE", "TOBOGGAN",
  "PIQUE-NIQUE", "BARBECUE", "CAMPING", "RANDONNÉE", "MOUSTIQUAIRE", "GOURDE", "BIVOUAC", "HAMAC",
];
